name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: IDENTITY
        environment: azurecloud
        enable-AzPSSession: false
        allow-no-subscriptions: false
        audience: api://AzureADTokenExchange
      env:
        TERRAFORM_CLI_PATH: /home/runner/work/_temp/$(uuidgen)

    # Add steps for Terraform or other deployments here
