name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        auth-type: IDENTITY
        environment: azurecloud
        enable-AzPSSession: false
        allow-no-subscriptions: false
        audience: api://AzureADTokenExchange
      env:
        AZURE_LOG_LEVEL: debug # Enable debug logs for troubleshooting
        TERRAFORM_CLI_PATH: /home/runner/work/_temp/$(uuidgen)
        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
